const Products = [
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 1,
    idCategory: 0,
    name: "Sprite Lata",
    description: "Sprite Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 2,
    idCategory: 0,
    name: "Fanta Laranja Lata",
    description: "Fanta Laranja Lata 350ml",
    price: 3.75,
    image: "",
  },
  {
    id: 3,
    idCategory: 0,
    name: "Guaraná Lata",
    description: "Guaraná Lata 350ml",
    price: 3.75,
    image: "",
  },
  {
    id: 4,
    idCategory: 0,
    name: "Água sem gás",
    description: "Água sem gás 350ml",
    price: 5.0,
    image: "",
  },
  {
    id: 5,
    idCategory: 0,
    name: "Água com gás",
    description: "Água com gás 350ml",
    price: 5.0,
    image: "",
  },
  {
    id: 6,
    idCategory: 0,
    name: "Coca-cola 2L",
    description: "Coca-cola 2L",
    price: 9.0,
    image: "",
  },
  {
    id: 7,
    idCategory: 0,
    name: "Guaraná 2L",
    description: "Guaraná 2L 350ml",
    price: 8.5,
    image: "",
  },
  {
    id: 8,
    idCategory: 0,
    name: "Água sem gás 2L",
    description: "Água sem gás 2L 350ml",
    price: 5.5,
    image: "",
  },
  {
    id: 9,
    idCategory: 0,
    name: "Cerveja",
    description: "Polar 350ml",
    price: 5.5,
    image: "",
  },
  {
    id: 10,
    idCategory: 0,
    name: "Cerveja",
    description: "Skol 350ml",
    price: 4.5,
    image: "",
  },
  {
    id: 12,
    idCategory: 0,
    name: "Cerveja",
    description: "Heineken 350ml",
    price: 7.4,
    image: "",
  },
  {
    id: 13,
    idCategory: 0,
    name: "Vodka",
    description: "Vodka Skavurska 1l",
    price: 16.4,
    image: "",
  },
  {
    id: 14,
    idCategory: 0,
    name: "Vodka",
    description: "Vodka Stalishnikova 1l",
    price: 25.5,
    image: "",
  },
  {
    id: 15,
    idCategory: 0,
    name: "Whisky",
    description: "Whisky El Patron 1l",
    price: 45.5,
    image: "",
  },
  {
    id: 16,
    idCategory: 1,
    name: "Arroz",
    description: "Arroz Tio Tobias 1kg",
    price: 4.75,
    image: "",
  },
  {
    id: 17,
    idCategory: 1,
    name: "Arroz",
    description: "Arroz Tio Tobias 5kg",
    price: 9.5,
    image: "",
  },
  {
    id: 18,
    idCategory: 1,
    name: "Feijão",
    description: "Arroz Tia Bela 1kg",
    price: 4.2,
    image: "",
  },
  {
    id: 19,
    idCategory: 1,
    name: "Feijão",
    description: "Arroz Tia Bela 5kg",
    price: 12.0,
    image: "",
  },
  {
    id: 20,
    idCategory: 1,
    name: "Óleo Girassol",
    description: "Óleo Girassol Campo Lindo 1l",
    price: 4.0,
    image: "",
  },
  {
    id: 21,
    idCategory: 1,
    name: "Óleo Canola",
    description: "Óleo Canola 1l",
    price: 3.0,
    image: "",
  },
  {
    id: 22,
    idCategory: 1,
    name: "Maionese",
    description: "Maionese Hellways 1l",
    price: 7.5,
    image: "",
  },
  {
    id: 23,
    idCategory: 1,
    name: "Maionese",
    description: "Maionese Hellways 1l",
    price: 7.5,
    image: "",
  },
  {
    id: 24,
    idCategory: 1,
    name: "Maionese",
    description: "Maionese Hellways 1l",
    price: 7.5,
    image: "",
  },
  {
    id: 25,
    idCategory: 1,
    name: "Ketchup",
    description: "Ketchup Hellways 1l",
    price: 7.5,
    image: "",
  },
  {
    id: 26,
    idCategory: 1,
    name: "Mostarda",
    description: "Mostarda Hellways 1l",
    price: 9.5,
    image: "",
  },
  {
    id: 27,
    idCategory: 1,
    name: "Farofa",
    description: "Farofa Temperada 1kg",
    price: 4.7,
    image: "",
  },
  {
    id: 28,
    idCategory: 1,
    name: "Café",
    description: "Café Peão 1kg",
    price: 6.75,
    image: "",
  },
  {
    id: 29,
    idCategory: 1,
    name: "Leite",
    description: "Leite Desnatado 1l",
    price: 3.75,
    image: "",
  },
  {
    id: 30,
    idCategory: 1,
    name: "Leite",
    description: "Leite Integral 1l",
    price: 4.75,
    image: "",
  },
  {
    id: 31,
    idCategory: 2,
    name: "Tomate",
    description: "Tomate Gaucho 1kg",
    price: 8.75,
    image: "",
  },
  {
    id: 32,
    idCategory: 2,
    name: "Limão",
    description: "Limão Siciliano 1kg",
    price: 6.75,
    image: "",
  },
  {
    id: 33,
    idCategory: 2,
    name: "Alface",
    description: "Alface Crespa - 1un",
    price: 2.0,
    image: "",
  },
  {
    id: 34,
    idCategory: 2,
    name: "Alface",
    description: "Alface Americana - 1un",
    price: 3.0,
    image: "",
  },
  {
    id: 35,
    idCategory: 2,
    name: "Cenoura",
    description: "Cenoura - 1kg",
    price: 4.5,
    image: "",
  },
  {
    id: 36,
    idCategory: 2,
    name: "Batata",
    description: "Batata - 1kg",
    price: 4.5,
    image: "",
  },
  {
    id: 37,
    idCategory: 2,
    name: "Cebola",
    description: "Cebola - 1kg",
    price: 6.75,
    image: "",
  },
  {
    id: 38,
    idCategory: 2,
    name: "Alho",
    description: "Cebola - 0,5kg",
    price: 10.75,
    image: "",
  },
  {
    id: 39,
    idCategory: 2,
    name: "Repolho",
    description: "Repolho - 1kg",
    price: 7.4,
    image: "",
  },
  {
    id: 40,
    idCategory: 2,
    name: "Couve-flor",
    description: "Couve-flor - 1un",
    price: 3.2,
    image: "",
  },
  {
    id: 41,
    idCategory: 2,
    name: "Brocolis",
    description: "Brocolis - 1un",
    price: 5.45,
    image: "",
  },
  {
    id: 42,
    idCategory: 2,
    name: "Maçã",
    description: "Maçã - 1kg",
    price: 3.55,
    image: "",
  },
  {
    id: 43,
    idCategory: 2,
    name: "Pêssego",
    description: "Pêssego - 1kg",
    price: 6.75,
    image: "",
  },
  {
    id: 44,
    idCategory: 2,
    name: "Pêra",
    description: "Pêra - 1kg",
    price: 4.55,
    image: "",
  },
  {
    id: 45,
    idCategory: 2,
    name: "Ameixa",
    description: "Ameixa - 1kg",
    price: 7.55,
    image: "",
  },
  {
    id: 46,
    idCategory: 3,
    name: "Pasta de dente",
    description: "Pasta de dente Colgate - 1un",
    price: 6.45,
    image: "",
  },
  {
    id: 47,
    idCategory: 3,
    name: "Desodorante",
    description: "Desodorante Rexona - 1un",
    price: 9.45,
    image: "",
  },
  {
    id: 48,
    idCategory: 3,
    name: "Sabonete",
    description: "Sabonete Neutro - 1un",
    price: 1.45,
    image: "",
  },
  {
    id: 49,
    idCategory: 3,
    name: "Papel Higiênico",
    description: "Papel Higiênico Neutro - 1un",
    price: 5.3,
    image: "",
  },
  {
    id: 50,
    idCategory: 3,
    name: "Enxaguante Bucal",
    description: "Enxaguante Bucal - 1un",
    price: 8.6,
    image: "",
  },
  {
    id: 51,
    idCategory: 3,
    name: "Shampoo",
    description: "Shampoo - 1un",
    price: 4.6,
    image: "",
  },
  {
    id: 52,
    idCategory: 3,
    name: "Condicionador",
    description: "Condicionador - 1un",
    price: 7.9,
    image: "",
  },
  {
    id: 53,
    idCategory: 3,
    name: "Escova de dente",
    description: "Escova de dente - 1un",
    price: 7.9,
    image: "",
  },
  {
    id: 54,
    idCategory: 3,
    name: "Lâmina de barbear",
    description: "Lâmina de barbear - 1un",
    price: 10.4,
    image: "",
  },
  {
    id: 55,
    idCategory: 3,
    name: "Creme Hidratante",
    description: "Creme Hidratante - 1un",
    price: 20.4,
    image: "",
  },
  {
    id: 56,
    idCategory: 3,
    name: "Abosorvente",
    description: "Abosorvente - 1un",
    price: 7.6,
    image: "",
  },
  {
    id: 57,
    idCategory: 3,
    name: "Pente para Cabelo",
    description: "Pente para Cabelo - 1un",
    price: 8.2,
    image: "",
  },
  {
    id: 58,
    idCategory: 3,
    name: "Creme para pentear",
    description: "Creme para pentear - 1un",
    price: 11.3,
    image: "",
  },
];

export default Products;
