const Products = [
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
];

export default Products;
