const Products = [
  {
    id: 0,
    idCategory: 0,
    name: "Coca-cola Lata",
    description: "Coca-cola Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 1,
    idCategory: 0,
    name: "Sprite Lata",
    description: "Sprite Lata 350ml",
    price: 3.5,
    image: "",
  },
  {
    id: 2,
    idCategory: 0,
    name: "Fanta Laranja Lata",
    description: "Fanta Laranja Lata 350ml",
    price: 3.75,
    image: "",
  },
  {
    id: 3,
    idCategory: 0,
    name: "Guaraná Lata",
    description: "Guaraná Lata 350ml",
    price: 3.75,
    image: "",
  },
  {
    id: 4,
    idCategory: 0,
    name: "Água sem gás",
    description: "Água sem gás 350ml",
    price: 5.0,
    image: "",
  },
  {
    id: 5,
    idCategory: 0,
    name: "Água com gás",
    description: "Água com gás 350ml",
    price: 5.0,
    image: "",
  },
  {
    id: 6,
    idCategory: 0,
    name: "Coca-cola 2L",
    description: "Coca-cola 2L",
    price: 9.0,
    image: "",
  },
  {
    id: 7,
    idCategory: 0,
    name: "Guaraná 2L",
    description: "Guaraná 2L 350ml",
    price: 8.5,
    image: "",
  },
  {
    id: 8,
    idCategory: 0,
    name: "Água sem gás 2L",
    description: "Água sem gás 2L 350ml",
    price: 5.5,
    image: "",
  },
];

export default Products;
